# Generated by Django 4.1.4 on 2022-12-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractQuarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('check_Out', models.DateTimeField()),
                ('check_In', models.DateTimeField()),
                ('facility', models.PositiveSmallIntegerField(choices=[(1, 'Doctor_Care'), (2, 'Free_WIFI'), (3, 'Media_Social_Service')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('map_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('abstractquarter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Quarter.abstractquarter')),
                ('Available', models.PositiveSmallIntegerField(choices=[(1, 'Available'), (2, 'Full')], default=1)),
            ],
            bases=('Quarter.abstractquarter',),
        ),
        migrations.CreateModel(
            name='General_Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='Quarter/hotel/avatar')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quarter.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='Quarter/quarter/avatar')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quarter.abstractquarter')),
            ],
        ),
        migrations.AddField(
            model_name='abstractquarter',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quarter.location'),
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('abstractquarter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Quarter.abstractquarter')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quarter.hotel')),
            ],
            bases=('Quarter.abstractquarter',),
        ),
    ]
